# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='balance.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbalance.proto\"\x1b\n\rSolicitudSend\x12\n\n\x02op\x18\x01 \x02(\x05\"\x1f\n\rRespuestaSend\x12\x0e\n\x06result\x18\x01 \x01(\t\" \n\x12SolicitudOperacion\x12\n\n\x02op\x18\x01 \x02(\x05\"$\n\x12RespuestaOperacion\x12\x0e\n\x06result\x18\x01 \x01(\t\"/\n\x0fSolicitudCreate\x12\x0e\n\x06nombre\x18\x01 \x02(\t\x12\x0c\n\x04ruta\x18\x02 \x02(\t\"\x1f\n\x0fRespuestaCreate\x12\x0c\n\x04\x63onf\x18\x01 \x01(\t\"-\n\rSolicitudRead\x12\x0e\n\x06nombre\x18\x01 \x02(\t\x12\x0c\n\x04ruta\x18\x02 \x02(\t\"\"\n\rRespuestaRead\x12\x11\n\tcontenido\x18\x01 \x01(\t\"A\n\x0eSolicitudWrite\x12\x0e\n\x06nombre\x18\x01 \x02(\t\x12\x11\n\tcontenido\x18\x02 \x02(\t\x12\x0c\n\x04ruta\x18\x03 \x02(\t\"\x1e\n\x0eRespuestaWrite\x12\x0c\n\x04\x63onf\x18\x01 \x01(\t\"0\n\x10SolicitudCreate2\x12\x0e\n\x06nombre\x18\x01 \x02(\t\x12\x0c\n\x04ruta\x18\x02 \x02(\t\" \n\x10RespuestaCreate2\x12\x0c\n\x04\x63onf\x18\x01 \x01(\t\".\n\x0eSolicitudRead2\x12\x0e\n\x06nombre\x18\x01 \x02(\t\x12\x0c\n\x04ruta\x18\x02 \x02(\t\"#\n\x0eRespuestaRead2\x12\x11\n\tcontenido\x18\x01 \x01(\t\"B\n\x0fSolicitudWrite2\x12\x0e\n\x06nombre\x18\x01 \x02(\t\x12\x11\n\tcontenido\x18\x02 \x02(\t\x12\x0c\n\x04ruta\x18\x03 \x02(\t\"\x1f\n\x0fRespuestaWrite2\x12\x0c\n\x04\x63onf\x18\x01 \x01(\t2\x89\x03\n\x07\x42\x61lance\x12*\n\x06SendOp\x12\x0e.SolicitudSend\x1a\x0e.RespuestaSend\"\x00\x12\x37\n\tOperacion\x12\x13.SolicitudOperacion\x1a\x13.RespuestaOperacion\"\x00\x12.\n\x06\x43reate\x12\x10.SolicitudCreate\x1a\x10.RespuestaCreate\"\x00\x12*\n\x04Read\x12\x0e.SolicitudRead\x1a\x0e.RespuestaRead\"\x00\x30\x01\x12+\n\x05Write\x12\x0f.SolicitudWrite\x1a\x0f.RespuestaWrite\"\x00\x12\x31\n\x07\x43reate2\x12\x11.SolicitudCreate2\x1a\x11.RespuestaCreate2\"\x00\x12-\n\x05Read2\x12\x0f.SolicitudRead2\x1a\x0f.RespuestaRead2\"\x00\x30\x01\x12.\n\x06Write2\x12\x10.SolicitudWrite2\x1a\x10.RespuestaWrite2\"\x00'
)




_SOLICITUDSEND = _descriptor.Descriptor(
  name='SolicitudSend',
  full_name='SolicitudSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='SolicitudSend.op', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=44,
)


_RESPUESTASEND = _descriptor.Descriptor(
  name='RespuestaSend',
  full_name='RespuestaSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='RespuestaSend.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=77,
)


_SOLICITUDOPERACION = _descriptor.Descriptor(
  name='SolicitudOperacion',
  full_name='SolicitudOperacion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='SolicitudOperacion.op', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=111,
)


_RESPUESTAOPERACION = _descriptor.Descriptor(
  name='RespuestaOperacion',
  full_name='RespuestaOperacion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='RespuestaOperacion.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=149,
)


_SOLICITUDCREATE = _descriptor.Descriptor(
  name='SolicitudCreate',
  full_name='SolicitudCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SolicitudCreate.nombre', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='SolicitudCreate.ruta', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=198,
)


_RESPUESTACREATE = _descriptor.Descriptor(
  name='RespuestaCreate',
  full_name='RespuestaCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conf', full_name='RespuestaCreate.conf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=231,
)


_SOLICITUDREAD = _descriptor.Descriptor(
  name='SolicitudRead',
  full_name='SolicitudRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SolicitudRead.nombre', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='SolicitudRead.ruta', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=278,
)


_RESPUESTAREAD = _descriptor.Descriptor(
  name='RespuestaRead',
  full_name='RespuestaRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contenido', full_name='RespuestaRead.contenido', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=314,
)


_SOLICITUDWRITE = _descriptor.Descriptor(
  name='SolicitudWrite',
  full_name='SolicitudWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SolicitudWrite.nombre', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contenido', full_name='SolicitudWrite.contenido', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='SolicitudWrite.ruta', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=381,
)


_RESPUESTAWRITE = _descriptor.Descriptor(
  name='RespuestaWrite',
  full_name='RespuestaWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conf', full_name='RespuestaWrite.conf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=413,
)


_SOLICITUDCREATE2 = _descriptor.Descriptor(
  name='SolicitudCreate2',
  full_name='SolicitudCreate2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SolicitudCreate2.nombre', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='SolicitudCreate2.ruta', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=463,
)


_RESPUESTACREATE2 = _descriptor.Descriptor(
  name='RespuestaCreate2',
  full_name='RespuestaCreate2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conf', full_name='RespuestaCreate2.conf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=497,
)


_SOLICITUDREAD2 = _descriptor.Descriptor(
  name='SolicitudRead2',
  full_name='SolicitudRead2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SolicitudRead2.nombre', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='SolicitudRead2.ruta', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=545,
)


_RESPUESTAREAD2 = _descriptor.Descriptor(
  name='RespuestaRead2',
  full_name='RespuestaRead2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contenido', full_name='RespuestaRead2.contenido', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=582,
)


_SOLICITUDWRITE2 = _descriptor.Descriptor(
  name='SolicitudWrite2',
  full_name='SolicitudWrite2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='SolicitudWrite2.nombre', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contenido', full_name='SolicitudWrite2.contenido', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='SolicitudWrite2.ruta', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=650,
)


_RESPUESTAWRITE2 = _descriptor.Descriptor(
  name='RespuestaWrite2',
  full_name='RespuestaWrite2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conf', full_name='RespuestaWrite2.conf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=683,
)

DESCRIPTOR.message_types_by_name['SolicitudSend'] = _SOLICITUDSEND
DESCRIPTOR.message_types_by_name['RespuestaSend'] = _RESPUESTASEND
DESCRIPTOR.message_types_by_name['SolicitudOperacion'] = _SOLICITUDOPERACION
DESCRIPTOR.message_types_by_name['RespuestaOperacion'] = _RESPUESTAOPERACION
DESCRIPTOR.message_types_by_name['SolicitudCreate'] = _SOLICITUDCREATE
DESCRIPTOR.message_types_by_name['RespuestaCreate'] = _RESPUESTACREATE
DESCRIPTOR.message_types_by_name['SolicitudRead'] = _SOLICITUDREAD
DESCRIPTOR.message_types_by_name['RespuestaRead'] = _RESPUESTAREAD
DESCRIPTOR.message_types_by_name['SolicitudWrite'] = _SOLICITUDWRITE
DESCRIPTOR.message_types_by_name['RespuestaWrite'] = _RESPUESTAWRITE
DESCRIPTOR.message_types_by_name['SolicitudCreate2'] = _SOLICITUDCREATE2
DESCRIPTOR.message_types_by_name['RespuestaCreate2'] = _RESPUESTACREATE2
DESCRIPTOR.message_types_by_name['SolicitudRead2'] = _SOLICITUDREAD2
DESCRIPTOR.message_types_by_name['RespuestaRead2'] = _RESPUESTAREAD2
DESCRIPTOR.message_types_by_name['SolicitudWrite2'] = _SOLICITUDWRITE2
DESCRIPTOR.message_types_by_name['RespuestaWrite2'] = _RESPUESTAWRITE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SolicitudSend = _reflection.GeneratedProtocolMessageType('SolicitudSend', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDSEND,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudSend)
  })
_sym_db.RegisterMessage(SolicitudSend)

RespuestaSend = _reflection.GeneratedProtocolMessageType('RespuestaSend', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTASEND,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaSend)
  })
_sym_db.RegisterMessage(RespuestaSend)

SolicitudOperacion = _reflection.GeneratedProtocolMessageType('SolicitudOperacion', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDOPERACION,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudOperacion)
  })
_sym_db.RegisterMessage(SolicitudOperacion)

RespuestaOperacion = _reflection.GeneratedProtocolMessageType('RespuestaOperacion', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTAOPERACION,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaOperacion)
  })
_sym_db.RegisterMessage(RespuestaOperacion)

SolicitudCreate = _reflection.GeneratedProtocolMessageType('SolicitudCreate', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDCREATE,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudCreate)
  })
_sym_db.RegisterMessage(SolicitudCreate)

RespuestaCreate = _reflection.GeneratedProtocolMessageType('RespuestaCreate', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTACREATE,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaCreate)
  })
_sym_db.RegisterMessage(RespuestaCreate)

SolicitudRead = _reflection.GeneratedProtocolMessageType('SolicitudRead', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDREAD,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudRead)
  })
_sym_db.RegisterMessage(SolicitudRead)

RespuestaRead = _reflection.GeneratedProtocolMessageType('RespuestaRead', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTAREAD,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaRead)
  })
_sym_db.RegisterMessage(RespuestaRead)

SolicitudWrite = _reflection.GeneratedProtocolMessageType('SolicitudWrite', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDWRITE,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudWrite)
  })
_sym_db.RegisterMessage(SolicitudWrite)

RespuestaWrite = _reflection.GeneratedProtocolMessageType('RespuestaWrite', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTAWRITE,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaWrite)
  })
_sym_db.RegisterMessage(RespuestaWrite)

SolicitudCreate2 = _reflection.GeneratedProtocolMessageType('SolicitudCreate2', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDCREATE2,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudCreate2)
  })
_sym_db.RegisterMessage(SolicitudCreate2)

RespuestaCreate2 = _reflection.GeneratedProtocolMessageType('RespuestaCreate2', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTACREATE2,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaCreate2)
  })
_sym_db.RegisterMessage(RespuestaCreate2)

SolicitudRead2 = _reflection.GeneratedProtocolMessageType('SolicitudRead2', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDREAD2,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudRead2)
  })
_sym_db.RegisterMessage(SolicitudRead2)

RespuestaRead2 = _reflection.GeneratedProtocolMessageType('RespuestaRead2', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTAREAD2,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaRead2)
  })
_sym_db.RegisterMessage(RespuestaRead2)

SolicitudWrite2 = _reflection.GeneratedProtocolMessageType('SolicitudWrite2', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDWRITE2,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:SolicitudWrite2)
  })
_sym_db.RegisterMessage(SolicitudWrite2)

RespuestaWrite2 = _reflection.GeneratedProtocolMessageType('RespuestaWrite2', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTAWRITE2,
  '__module__' : 'balance_pb2'
  # @@protoc_insertion_point(class_scope:RespuestaWrite2)
  })
_sym_db.RegisterMessage(RespuestaWrite2)



_BALANCE = _descriptor.ServiceDescriptor(
  name='Balance',
  full_name='Balance',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=686,
  serialized_end=1079,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendOp',
    full_name='Balance.SendOp',
    index=0,
    containing_service=None,
    input_type=_SOLICITUDSEND,
    output_type=_RESPUESTASEND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Operacion',
    full_name='Balance.Operacion',
    index=1,
    containing_service=None,
    input_type=_SOLICITUDOPERACION,
    output_type=_RESPUESTAOPERACION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='Balance.Create',
    index=2,
    containing_service=None,
    input_type=_SOLICITUDCREATE,
    output_type=_RESPUESTACREATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='Balance.Read',
    index=3,
    containing_service=None,
    input_type=_SOLICITUDREAD,
    output_type=_RESPUESTAREAD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='Balance.Write',
    index=4,
    containing_service=None,
    input_type=_SOLICITUDWRITE,
    output_type=_RESPUESTAWRITE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create2',
    full_name='Balance.Create2',
    index=5,
    containing_service=None,
    input_type=_SOLICITUDCREATE2,
    output_type=_RESPUESTACREATE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Read2',
    full_name='Balance.Read2',
    index=6,
    containing_service=None,
    input_type=_SOLICITUDREAD2,
    output_type=_RESPUESTAREAD2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write2',
    full_name='Balance.Write2',
    index=7,
    containing_service=None,
    input_type=_SOLICITUDWRITE2,
    output_type=_RESPUESTAWRITE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BALANCE)

DESCRIPTOR.services_by_name['Balance'] = _BALANCE

# @@protoc_insertion_point(module_scope)
